[tool.poetry]
name = "client-service"
version = "0.1.0"
description = "gRPC Client Service"
authors = ["Your Name"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependencies]
python = "^3.8"
grpcio = "^1.34.1"
grpcio-tools = "^1.34.1"
